esphome:
  name: esp32-ble-beacon

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Metatool1 Fallback Hotspot"
    password: "DJjwCeDQqMD1"

captive_portal:

web_server:
  port: 80

ota:
  - platform: esphome
    password: ""

# BLE Beacon Config
esp32_ble_beacon:
  type: iBeacon
  uuid: !secret ble_beacon_uuid
  major: 2
  minor: 3
  measured_power: -59

# MQTT Configuration
mqtt:
  broker: io.adafruit.com
  username: sebschlo
  password: !secret mqtt_password
  discovery: false
  discover_ip: false
  topic_prefix: sebschlo/feeds
  log_topic: null
  keepalive: 5s
  on_message:
    topic: sebschlo/feeds/beacon-users
    then:
      - lambda: |-
          ESP_LOGD("mqtt", "Received ada message: %s", x.c_str());
  birth_message:
    topic: sebschlo/feeds/beacon-users
    payload: "Connected successfully"
  will_message:
    topic: sebschlo/feeds/beacon-users
    payload: "Disconnected"


# http_request:
#   useragent: esphome/device
#   verify_ssl: false

# interval:
#   - interval: 60s
#     then:
#       - http_request.get:
#           url: http://herokuapp.com
#           headers:
#             Content-Type: application/json
#           on_response:
#             then:
#               - logger.log:
#                   format: "Response status: %d, Duration: %u ms"
#                   args:
#                     - response->status_code
#                     - response->duration_ms
