esphome:
  name: esp32_ble_beacon

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Metatool1 Fallback Hotspot"
    password: "DJjwCeDQqMD1"

captive_portal:

  # Example configuration entry
web_server:
  port: 80

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

esp32_ble_beacon:
  type: iBeacon
  uuid: !secret ble_beacon_uuid
  major: 2
  minor: 3
  measured_power: -59

# Optional: You can add more sensors or components here
